channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - pip
  - adapterremoval==2.3.2
  - samtools==1.6
  - picard==2.24.2
  - bowtie2==2.3.0
  - bwa==0.7.17
  - mapdamage2==2.2.1
  - pysam==0.16.0
  - r-base
  - r-rcpp
  - r-rcppgsl
  - r-gam
  - r-inline
  - pip:
    - paleomix==1.3.2
